query pairIndicators($exchange: String!, $pair: String!) {
  pairIndicators(Exchange: $exchange, Pair: $pair) {
    Exchange,
    Pair,
    Base_balance,
    Quote_balance,
    On_Orders,
    Bid,
    Ask,
    Sell,
    Break_point,
    Bought_avg,
    Status_message,
    Bought_volume,
    Price,
    Sold_volume,
    Averaged_down_volume,
    Open_order,
    Last_order,
    EMA1,
    EMA2,
    LowBB,
    HighBB,
    SMA,
    Status_message1,
    Status_message2,
    GB_status
  }
}
